// Dados das Instituições Financeiras
const bankData = [
   { posicao: 1, instituicao: "BANCO DO BRASIL S.A.", taxa_anual: "10,06%", taxa_mensal: "0,80%" },
   { posicao: 2, instituicao: "CAIXA ECONÔMICA FEDERAL", taxa_anual: "10,50%", taxa_mensal: "0,84%" },
   { posicao: 3, instituicao: "ITAÚ UNIBANCO S.A.", taxa_anual: "10,80%", taxa_mensal: "0,86%" },
   { posicao: 4, instituicao: "BRADESCO S.A.", taxa_anual: "11,20%", taxa_mensal: "0,89%" },
   { posicao: 5, instituicao: "SANTANDER BRASIL S.A.", taxa_anual: "11,50%", taxa_mensal: "0,91%" },
   { posicao: 6, instituicao: "BANCO SAFRA S.A.", taxa_anual: "11,80%", taxa_mensal: "0,94%" },
   { posicao: 7, instituicao: "BANCO VOTORANTIM S.A.", taxa_anual: "12,00%", taxa_mensal: "0,95%" },
   { posicao: 8, instituicao: "BANCO INTER S.A.", taxa_anual: "12,30%", taxa_mensal: "0,98%" },
   { posicao: 9, instituicao: "BANCO ORIGINAL S.A.", taxa_anual: "12,50%", taxa_mensal: "0,99%" },
   { posicao: 10, instituicao: "BANCO NUBANK S.A.", taxa_anual: "12,80%", taxa_mensal: "1,01%" },
   { posicao: 11, instituicao: "BANCO MERCANTIL DO BRASIL S.A.", taxa_anual: "13,00%", taxa_mensal: "1,03%" },
   { posicao: 12, instituicao: "BANCO BMGBMG S.A.", taxa_anual: "13,20%", taxa_mensal: "1,04%" },
   { posicao: 13, instituicao: "BANCO SOFISA S.A.", taxa_anual: "13,50%", taxa_mensal: "1,07%" },
   { posicao: 14, instituicao: "BANCO PINE S.A.", taxa_anual: "13,80%", taxa_mensal: "1,09%" },
   { posicao: 15, instituicao: "BANCO MODAL S.A.", taxa_anual: "14,00%", taxa_mensal: "1,11%" },
   { posicao: 16, instituicao: "BANCO FIBRA S.A.", taxa_anual: "14,20%", taxa_mensal: "1,12%" },
   { posicao: 17, instituicao: "BANCO CAPITAL S.A.", taxa_anual: "14,50%", taxa_mensal: "1,15%" },
   { posicao: 18, instituicao: "BANCO FINTEC S.A.", taxa_anual: "14,80%", taxa_mensal: "1,17%" },
   { posicao: 19, instituicao: "BANCO MASTER S.A.", taxa_anual: "15,00%", taxa_mensal: "1,19%" },
   { posicao: 20, instituicao: "BANCO TOPÁZIO S.A.", taxa_anual: "15,20%", taxa_mensal: "1,20%" },
   { posicao: 21, instituicao: "BANCO INDUSVAL S.A.", taxa_anual: "15,50%", taxa_mensal: "1,23%" },
   { posicao: 22, instituicao: "BANCO INVESTCRED S.A.", taxa_anual: "15,80%", taxa_mensal: "1,25%" },
   { posicao: 23, instituicao: "BANCO FOMPE S.A.", taxa_anual: "16,00%", taxa_mensal: "1,27%" },
   { posicao: 24, instituicao: "BANCO ALFA S.A.", taxa_anual: "16,20%", taxa_mensal: "1,28%" },
   { posicao: 25, instituicao: "BANCO SEMEAR S.A.", taxa_anual: "16,50%", taxa_mensal: "1,31%" },
   { posicao: 26, instituicao: "BANCO DAYCOVAL S.A.", taxa_anual: "16,80%", taxa_mensal: "1,33%" },
   { posicao: 27, instituicao: "BANCO CETESDIRETO S.A.", taxa_anual: "17,00%", taxa_mensal: "1,35%" },
   { posicao: 28, instituicao: "BANCO CRESFIBANK S.A.", taxa_anual: "17,20%", taxa_mensal: "1,36%" },
   { posicao: 29, instituicao: "BANCO TRIBANCO S.A.", taxa_anual: "17,50%", taxa_mensal: "1,39%" },
   { posicao: 30, instituicao: "BANCO BANESE S.A.", taxa_anual: "17,80%", taxa_mensal: "1,41%" },
   { posicao: 31, instituicao: "BANCO BANESTES S.A.", taxa_anual: "18,00%", taxa_mensal: "1,43%" },
   { posicao: 32, instituicao: "BANCO BANRISUL S.A.", taxa_anual: "18,20%", taxa_mensal: "1,44%" },
   { posicao: 33, instituicao: "BANCO BRADESCO CARTÕES S.A.", taxa_anual: "18,50%", taxa_mensal: "1,47%" },
   { posicao: 34, instituicao: "BANCO ITAUCARD S.A.", taxa_anual: "18,80%", taxa_mensal: "1,49%" },
   { posicao: 35, instituicao: "BANCO SANTANDER CARTÕES S.A.", taxa_anual: "19,00%", taxa_mensal: "1,51%" },
   { posicao: 36, instituicao: "BANCO CETESDIRETO S.A.", taxa_anual: "19,20%", taxa_mensal: "1,52%" },
   { posicao: 37, instituicao: "BANCO CRESFIBANK S.A.", taxa_anual: "19,50%", taxa_mensal: "1,55%" },
   { posicao: 38, instituicao: "BANCO TRIBANCO S.A.", taxa_anual: "19,80%", taxa_mensal: "1,57%" },
   { posicao: 39, instituicao: "BANCO BANESE S.A.", taxa_anual: "20,00%", taxa_mensal: "1,59%" },
   { posicao: 40, instituicao: "BANCO BANESTES S.A.", taxa_anual: "20,20%", taxa_mensal: "1,60%" },
   { posicao: 41, instituicao: "BANCO BANRISUL S.A.", taxa_anual: "20,50%", taxa_mensal: "1,63%" },
   { posicao: 42, instituicao: "BANCO BRADESCO CARTÕES S.A.", taxa_anual: "20,80%", taxa_mensal: "1,65%" },
   { posicao: 43, instituicao: "BCO RNX S.A.", taxa_anual: "0,00%", taxa_mensal: "0,00%" }
];

